# Generated by Django 2.1.7 on 2020-04-11 17:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.upload
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='AutoMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='AutoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
        migrations.CreateModel(
            name='AutoSaloon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=10000, verbose_name='Описание')),
                ('views', models.PositiveIntegerField(verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Автосалон',
                'verbose_name_plural': 'Автосалоны',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='ClassCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('type_of', models.PositiveSmallIntegerField(choices=[(1, 'Микроавтомобили'), (2, 'Малыеавтомобили'), (3, 'Гольф класс'), (4, 'Средний класс'), (5, 'Бизнес класс'), (6, 'Представительский класс'), (7, 'Кроссоверы, внедорожники'), (8, 'Минивэны'), (9, 'Купе, кабриолеты и родстеры')], verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Класс машины',
                'verbose_name_plural': 'Классы машин',
            },
        ),
        migrations.CreateModel(
            name='Complectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, verbose_name='Название')),
                ('color', models.PositiveSmallIntegerField(choices=[(1, 'БЕЛЫЙ'), (2, 'ЧЕРНЫЙ'), (3, 'СЕРЫЙ'), (4, 'СИНИЙ'), (5, 'КРАСНЫЙ'), (6, 'ЗЕЛЕНЫЙ'), (7, 'КОРИЧНЕВЫЙ'), (8, 'ЖЕЛТЫЙ'), (9, 'ОРАНЖЕВЫЙ')], default=1, verbose_name='Цвет')),
                ('description_color', models.CharField(max_length=255, verbose_name='Описание цвета')),
                ('engine_size', models.FloatField(verbose_name='Объем двигателя')),
                ('power', models.PositiveIntegerField(verbose_name='Мощность в л.с')),
                ('torque', models.PositiveIntegerField(verbose_name='Момент в Н.м')),
                ('drive_train', models.PositiveSmallIntegerField(choices=[(1, 'ЗАДНИЙ'), (2, 'ПЕРЕДНИЙ'), (3, 'ПОДКЛЮЧАЕМЫЙ ПОЛНЫЙ'), (4, 'ПОСТОЯННЫЙ ПОЛНЫЙ')], default=2, verbose_name='Привод')),
                ('gearbox', models.PositiveSmallIntegerField(choices=[(1, 'АКПП'), (2, 'МЕХАНИКА'), (3, 'РОБОТ'), (4, 'ВАРИАТОР')], default=1, verbose_name='КПП')),
                ('gears_number', models.PositiveSmallIntegerField(verbose_name='Число скоростей')),
                ('acceleration', models.FloatField(verbose_name='Разгон до 100 км/ч')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('quantity', models.PositiveIntegerField(verbose_name='Кол-во')),
                ('auto_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complectations', to='main.AutoModel', verbose_name='Модель')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comps', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комплектация',
                'verbose_name_plural': 'Комплектации',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=10000)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to=utils.upload.offer_image_path, validators=[utils.validators.validate_file_size, utils.validators.validate_extension], verbose_name='Фото')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('views', models.PositiveIntegerField(verbose_name='Просмотры')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Опубликован в')),
                ('phone', models.CharField(max_length=16, verbose_name='Номер телефона')),
                ('auto_saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comps', to='main.AutoSaloon', verbose_name='Автосалон')),
                ('complectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='main.Complectation', verbose_name='Комплектация')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('discounts', models.ManyToManyField(default=None, to='main.Discount', verbose_name='Акции')),
                ('images', models.ManyToManyField(to='main.Image', verbose_name='Фотографии')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.PositiveSmallIntegerField(choices=[(1, 'КЛЮЧЕВЫЕ ОПЦИИ'), (2, 'ГАРАНТИЯ'), (3, 'ЭКСТЕРЬЕР'), (4, 'ИНТЕРЬЕР'), (5, 'МУЛЬТИМЕДИА'), (6, 'БЕЗОПАСНОСТЬ'), (7, 'КОМФОРТ'), (8, 'ТЕХНИЧЕСКИЕ ОСОБЕННОСТИ'), (9, 'ОБЗОР И ФАРЫ'), (10, 'ДОПОЛНИТЕЛЬНО')], default=10, verbose_name='Вид опции')),
                ('name', models.CharField(max_length=550, verbose_name='Название')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Опция',
                'verbose_name_plural': 'Опции',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='options',
            field=models.ManyToManyField(to='main.Option', verbose_name='Опции'),
        ),
        migrations.AddField(
            model_name='autosaloon',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saloons', to='main.City', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='autosaloon',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saloons', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='autosaloon',
            name='images',
            field=models.ManyToManyField(to='main.Image', verbose_name='Фотографии'),
        ),
        migrations.AddField(
            model_name='autosaloon',
            name='marks',
            field=models.ManyToManyField(to='main.AutoMark', verbose_name='Марки'),
        ),
        migrations.AddField(
            model_name='automodel',
            name='class_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='main.ClassCar', verbose_name='Класс машины'),
        ),
        migrations.AddField(
            model_name='automodel',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='automodel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='main.Image', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='automodel',
            name='manufactured_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.Country', verbose_name='Собран в'),
        ),
        migrations.AddField(
            model_name='automodel',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.AutoMark', verbose_name='Марка машины'),
        ),
        migrations.AddField(
            model_name='automark',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='main.Image', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='application',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='main.Offer', verbose_name='Предложение'),
        ),
    ]
